@echo off

echo Making a GET request to the API to check goal actions...
call axiosCheckActions.bat

echo Building the project...
call build.bat || echo Build failed, continuing with the script...

echo Starting the project with PM2...
call startpm2.bat || echo Failed to start PM2, continuing with the script...

echo Running auto_build.bat...
call auto_build.bat